version: '1'
services:
  cloudrm:
    image: cloudrm_image
    command: sh -c "pip install -r requirements.txt && apt-get update && apt install -y libgl1-mesa-glx && python app.py"
    build: .
    ports: 
      - "8888:8080"
    working_dir: /home
    volumes: 
      - ./:/home
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: cloudrm_DB
  mysql:
    image: mysql:8.0
    volumes: 
      - cloudrm_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cloudrm_DB

volumes:
  cloudrm_mysql:

